# Generated by Django 3.0.3 on 2020-07-19 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('adresse', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'domaines',
            },
        ),
        migrations.CreateModel(
            name='Millesime',
            fields=[
                ('annee', models.IntegerField(primary_key=True, serialize=False)),
                ('nomMillesime', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'millesime',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('domaines', models.ManyToManyField(blank=True, to='administration.Domaine')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organisation',
            },
        ),
        migrations.CreateModel(
            name='Personnels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Organisation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
