# Generated by Django 3.0.3 on 2020-07-19 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='millesime',
            name='orga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Organisation'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='millesime',
            table='millesimes',
        ),
    ]
