# Generated by Django 3.0.3 on 2020-07-19 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'materiels',
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numIlot', models.IntegerField()),
                ('nomParcelle', models.CharField(max_length=50)),
                ('appellation', models.CharField(max_length=50)),
                ('proprietaire', models.CharField(max_length=50)),
                ('surface', models.FloatField()),
                ('commune', models.CharField(max_length=50)),
                ('refCadastre', models.CharField(max_length=50)),
                ('anneesPlantation', models.CharField(max_length=50)),
                ('datebio', models.IntegerField()),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Domaine')),
            ],
            options={
                'db_table': 'parcelles',
            },
        ),
    ]
