# Generated by Django 3.0.3 on 2020-07-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20200719_2348'),
        ('entrants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelle',
            name='domaine',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='surface',
        ),
        migrations.CreateModel(
            name='ParcelleEtendue',
            fields=[
                ('proprietaire', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('surface', models.FloatField()),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Domaine')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrants.Parcelle')),
            ],
            options={
                'db_table': 'parcelle-domaines',
            },
        ),
        migrations.AddField(
            model_name='parcelle',
            name='domaines',
            field=models.ManyToManyField(through='entrants.ParcelleEtendue', to='administration.Domaine'),
        ),
    ]
