# Generated by Django 3.0.3 on 2020-07-20 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20200719_2348'),
        ('entrants', '0002_auto_20200720_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiels',
            name='orga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Organisation'),
            preserve_default=False,
        ),
    ]
