# Generated by Django 3.0.3 on 2020-07-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrants', '0004_cuve_historicalcuve_historicalmateriels_historicalparcelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelleetendue',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcelleetendue',
            name='proprietaire',
            field=models.CharField(max_length=40),
        ),
    ]
