# Generated by Django 3.0.3 on 2020-03-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'materiels',
            },
        ),
    ]
