# Generated by Django 3.0.3 on 2020-02-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millesimes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='millesime',
            name='id',
        ),
        migrations.AlterField(
            model_name='millesime',
            name='annee',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
