# Generated by Django 3.0.3 on 2021-01-17 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20200719_2348'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAction', models.DateTimeField()),
                ('millesime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Millesime')),
                ('orga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Organisation')),
            ],
            options={
                'db_table': 'operations',
            },
        ),
        migrations.CreateModel(
            name='Assemblage',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cave.Operation')),
            ],
            options={
                'db_table': 'assemblages',
            },
            bases=('cave.operation',),
        ),
        migrations.CreateModel(
            name='HistoricalOperation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dateAction', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('millesime', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.Millesime')),
                ('orga', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.Organisation')),
            ],
            options={
                'verbose_name': 'historical operation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAssemblage',
            fields=[
                ('operation_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='cave.Operation')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('dateAction', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('millesime', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.Millesime')),
                ('orga', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.Organisation')),
            ],
            options={
                'verbose_name': 'historical assemblage',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AssemblageLots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cave.Lot')),
                ('assemblage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cave.Assemblage')),
            ],
            options={
                'db_table': 'assemblage-lots',
            },
        ),
        migrations.AddField(
            model_name='assemblage',
            name='lots',
            field=models.ManyToManyField(blank=True, through='cave.AssemblageLots', to='cave.Lot'),
        ),
    ]
