# Generated by Django 3.0.3 on 2020-07-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBenne', models.IntegerField()),
                ('idMillesime', models.IntegerField()),
                ('dateRecep', models.DateTimeField()),
                ('densite', models.FloatField()),
                ('temperature', models.FloatField()),
                ('alcProb', models.FloatField()),
                ('so2', models.FloatField()),
                ('autre1', models.CharField(blank=True, max_length=40)),
                ('autre2', models.CharField(blank=True, max_length=40)),
                ('meteo', models.CharField(max_length=10)),
                ('pourcentSO2', models.FloatField()),
                ('idOperateur', models.IntegerField()),
                ('idMateriel', models.IntegerField()),
                ('parcelles', models.ManyToManyField(blank=True, to='entrants.Parcelle')),
            ],
            options={
                'db_table': 'benne',
            },
        ),
        migrations.CreateModel(
            name='Marc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMarc', models.IntegerField()),
                ('idMillesime', models.IntegerField()),
                ('volumeMarc', models.FloatField()),
                ('idMateriel', models.IntegerField()),
                ('bennes', models.ManyToManyField(blank=True, to='vendange.Benne')),
            ],
            options={
                'db_table': 'marc',
            },
        ),
    ]
