# Generated by Django 3.0.3 on 2020-07-20 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrants', '0003_materiels_orga'),
        ('administration', '0002_auto_20200719_2348'),
        ('vendange', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benne',
            old_name='autre1',
            new_name='commentaire',
        ),
        migrations.RemoveField(
            model_name='benne',
            name='autre2',
        ),
        migrations.RemoveField(
            model_name='benne',
            name='idMillesime',
        ),
        migrations.AddField(
            model_name='benne',
            name='millesime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Millesime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benne',
            name='orga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.Organisation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benne',
            name='idMateriel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrants.Materiels'),
        ),
        migrations.AlterField(
            model_name='benne',
            name='idOperateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
