# Generated by Django 3.0.3 on 2020-02-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numIlot', models.IntegerField()),
                ('nomParcelle', models.CharField(max_length=50)),
                ('appellation', models.CharField(max_length=50)),
                ('domaine', models.CharField(max_length=50)),
                ('surface', models.FloatField()),
            ],
            options={
                'db_table': 'parcelle',
            },
        ),
    ]
