# Generated by Django 3.0.3 on 2020-02-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelle',
            name='id',
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='numIlot',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
