# Generated by Django 3.0.3 on 2020-02-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBenne', models.IntegerField()),
                ('idMillesime', models.IntegerField()),
                ('dateRecep', models.DateTimeField()),
                ('densite', models.FloatField()),
                ('temperature', models.FloatField()),
                ('alcProb', models.FloatField()),
                ('so2', models.FloatField()),
                ('autre1', models.CharField(blank=True, max_length=40)),
                ('autre2', models.CharField(blank=True, max_length=40)),
                ('meteo', models.CharField(max_length=10)),
                ('pourcentSO2', models.FloatField()),
                ('idOperateur', models.IntegerField()),
                ('idMateriel', models.IntegerField()),
                ('parcelles', models.ManyToManyField(blank=True, related_name='parcelles_par_benne', to='parcelles.Parcelle')),
            ],
            options={
                'db_table': 'benne',
            },
        ),
    ]
